#!/usr/bin/env node
// AUTO-GENERATED SOURCE — este script escribe src/game/config.ts.
// Corre esto cada vez que math-sdk regenere config_fe_umbral_portal.json.
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE_JSON = join(
	__dirname,
	'../../../../math-sdk/games/umbral_portal/library/configs/config_fe_umbral_portal.json',
);
const OUTPUT_TS = join(__dirname, '../src/game/config.ts');

const raw = JSON.parse(readFileSync(SOURCE_JSON, 'utf-8'));

// math-sdk emite `symbols` como un array de objetos de una sola clave
// (p.ej. [{"H1": {...}}, {"L2": {...}}]); el frontend lo consume como un
// solo objeto indexado por nombre de símbolo.
const symbols = {};
for (const entry of raw.symbols) {
	const [name, value] = Object.entries(entry)[0];
	symbols[name] = value;
}

const output = {
	providerName: raw.providerName,
	gameName: raw.gameName,
	gameID: raw.gameID,
	rtp: raw.rtp,
	numReels: raw.numReels,
	numRows: raw.numRows,
	betModes: raw.betModes,
	symbols,
	paddingReels: raw.paddingReels,
};

const fileContent = `// AUTO-GENERATED by scripts/sync-config.mjs — no editar a mano.
// Fuente de verdad: math-sdk/games/umbral_portal/library/configs/config_fe_umbral_portal.json
// Para regenerar tras un cambio en math-sdk: node scripts/sync-config.mjs

export default ${JSON.stringify(output, null, '\t')};
`;

writeFileSync(OUTPUT_TS, fileContent);
console.log(`Wrote ${OUTPUT_TS}`);
